spring:
  config:
    import:
      - classpath:/external/external.yaml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB