spring:
  config:
    import:
      - classpath:/external/external.yaml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
        show_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    org.org.hibernate.SQL: debug
    org.org.hibernate: trace
